packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - 'prisma'
  - 'esbuild'

overrides:
  react-native-worklets: 0.10.1
  react-native-reanimated: 4.5.1

